load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["parser.go"],
    importpath = "github.com/buildbuddy-io/buildbuddy-cli/parser",
    visibility = ["//visibility:public"],
    deps = ["//logging:go_default_library"],
)
